spring.application.name=legacy-batch-migrator

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/lab_batch
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Spring Batch
spring.batch.jdbc.initialize-schema=always
# Enable Spring Batch to run the job automatically on startup
spring.batch.job.enabled=true

 spring.batch.job.name=reporteTransaccionesJob
# spring.batch.job.name=calculoInteresesJob
# spring.batch.job.name=generacionEstadosCuentaJob

bancoxyz.task-executor.core-pool-size=3
bancoxyz.task-executor.max-pool-size=3
bancoxyz.task-executor.queue-capacity=10